### PR TITLE
Add CUDA build to GitHub Actions (and CMake clean-up)

### PR DESCRIPTION
**Pull request by KrisThielemans**
- add a GHA build with CUDA, whcih needed renaming of caches
- add missing source extensions in some CMakeLists.txt

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@markus-jehl this works all ok, but it is the first time that we test gcc 12 with CUDA on GHA. Sadly `test_interpolate_projdata` fails
https://github.com/UCL/STIR/actions/runs/7219366591/job/19670252356#step:10:165
```
INFO: Performing symmetric interpolation test for Cylindrical scanner
INFO: Determined voxel size by dividing default_bin_size (6.52531) by zoom
WARNING: Disabling symmetries as image is rotated due to phi offset of the scanner.
WARNING: forward_project. Imaging modality unknown for either the image or the projection data or both.
Going ahead anyway.
Error : 6.3685 is larger than 0.00089545, symmetry errors larger than 0.01% of absolute values in axial direction
```
the "blocks" test works. Any idea?

(By the way, we need to set modality in these tests to avoid at least some warnings.)

**Comment by KrisThielemans** [comment]
Left gcc-12, right gcc-11
image

@markus-jehl @danieldeidda any ideas?

**Comment by markus-jehl** [comment]
How does the downsampled sinogram look? If that one is still symmetric, then it is definitely in the interpolation. Otherwise it must be some difference in how float numbers are rounded

**Comment by KrisThielemans** [comment]
it's the downsampled data. left is gcc-12
image

**Comment by markus-jehl** [comment]
This is very strange... I looked at the scanner definitions and the math checks out as far as I can tell. So it must be some weird floating point issue in how the cylinder is constructed for the downsampled scanner or similar.

**Comment by KrisThielemans** [comment]
no problem in Debug build

**Comment by KrisThielemans** [comment]
downsampled image in Debug mode occupies central 3 planes (out of 11). In RelWithDebug, it has 1 more non-zero plane, causing asymmetry.

**Comment by KrisThielemans** [comment]
for the cylindrical scanner, the z-voxel size is 10mm, but the length of the cylinder is 40. So, this is sensitive to rounding.

**Comment by KrisThielemans** [comment]
Should be fixed. @markus-jehl please have a look.

**Comment by markus-jehl** [comment]
That looks clean, thank you!

**Pull request merged**
