### PR TITLE
DiscretisedDensity write_to_file and python example

### LINKED ISSUE #952: Write to file for VoxelsOnCartesianGrid
The `ProjData` structure has a method `read_from_file` and a method `write_to_file`. However, the `VoxelsOnCartesianGrid` structure has a method `read_from_file` but no method `write_to_file`. 

Comments:
- it's possible to use `stir.write_image_to_file(filename, VoxelsOnCartesianGrid)` in Python
- there is no example of this in the python recon examples

### PR DESCRIPTION
**Pull request by robbietuk**
Fixes #952 and adds example usage to `recon_demo.py`

### CODE REVIEW

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
Thanks but I do not want to modify the C++ code. This creates (even more) circular dependencies between io and buildblock, which we should remove. Instead, we should add it in `stir.i` via `%extend`, like we do for `read_from_file` https://github.com/UCL/STIR/blob/84e4ddc6eb69621bc14af7ed3662febe52b180df/src/swig/stir.i#L963

**Comment by robbietuk** [comment]
This took an embarrassingly long time to figure out extend and swig but it works for me now 😄

**Review by KrisThielemans — APPROVED** [review]

**Comment by KrisThielemans** [comment]
looks good. let's wait for the tests.

Can you add a line in the latest release notes? Sadly probably means merging `master` into here as otherwise you won't have them (and we'd have conflicts).

**Comment by robbietuk** [comment]
All should be good. These three comits were made since a rebase onto master today. There should not be a conflict.

**Pull request merged**
