### PR TITLE
Changing error handling to throw runtime_error instead of string.

### PR DESCRIPTION
**Pull request by markus-jehl**

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Appveyor error was due to a bug introduced by myself. not sure why I hadn't seen it on Appveyor previously. It should be fixed in 63c2e9c6d505fe131d5766ff5f68188c9fb98bd5

Please merge `master` in here (if the above commit worked). We'll also need some new release notes, but I wouldn't know what version to call it yet!

**Comment by markus-jehl** [comment]
Perfect, thanks. I merged master now. Will be away all of next week, so you have a bit of time to work out the version number ;-)

**Comment by KrisThielemans** [comment]
@markus-jehl can you please merge `master` again, and update the `release_5.2.htm`?

@evgueni-ovtchinnikov will this affect SIRF? (depends on how you catch STIR exceptions). Maybe you can check SIRF with this branch?

**Comment by markus-jehl** [comment]
Done! The failed test is because some server appears to have been down.

**Comment by KrisThielemans** [comment]
Great. I re-ran the job and it's fine. waiting for @evgueni-ovtchinnikov's input.

**Comment by evgueni-ovtchinnikov** [comment]
I found exactly one occasion of `catch(std::string msg)` in SIRF and replaced it with `catch(…)`, so I do not expect any SIRF problems with this PR merged.

**Comment by KrisThielemans** [comment]
thanks @evgueni-ovtchinnikov

**Pull request merged**
