### PR TITLE
simplify multiply_crystal_factors

### PR DESCRIPTION
**Pull request by KrisThielemans**
Just use `get_all_det_pos_pairs_for_bin()` as opposed to complicated logic. However, there are no tests for this sadly. We should add some.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@danieldeidda this compiles ok. I haven't actually run it yet...

**Comment by danieldeidda** [comment]
I run it on ProjDataCylindrical and get the following error:
construct_randoms_from_singles: /home/nmdicom-recon/devel/crystal_multipl_branch/STIR-1/src/include/stir/VectorWithOffset.inl:114: T& stir::VectorWithOffset<T>::operator[](int) [with T = stir::VectorWithOffset<stir::ProjDataInfoCylindricalNoArcCorr::Det1Det2>]: Assertion `i<=this->get_max_index()' failed.

here:
https://github.com/UCL/STIR/blob/master/src/buildblock/ProjDataInfoCylindricalNoArcCorr.cxx#L356-L357

**Comment by danieldeidda** [comment]
the issue seems to be the same view_num and tang_pos are not initialised in proj_data_info_ptr->get_all_det_pos_pairs_for_bin(det_pos_pairs, bin); 

but they are in  parallel_bin

                    parallel_bin.view_num() = view_num;
                    parallel_bin.tangential_pos_num() = tangential_pos_num;
should we pass parallel bin instead then?

**Comment by KrisThielemans** [comment]
yes indeed! great. I think you should be able to push to this branch.

**Comment by KrisThielemans** [comment]
appveyor failure was a time-out

**Comment by danieldeidda** [comment]
the results are the same of the old code:

image

**Comment by KrisThielemans** [comment]
Perfect. I'll merge this then and work on some tests later. Thanks!

**Pull request merged**
