### PR TITLE
Spect stir

### PR DESCRIPTION
**Pull request by danieldeidda**
Create a set of base classes for ListMode and derive SPECT and PET functionality from it.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
I'm a bit confused. the previous commit seems to have removed code from `get_bin_efficiency` and put it back in `apply/undo`. intentional?

**Comment by danieldeidda** [comment]
> I'm a bit confused. the previous commit seems to have removed code from `get_bin_efficiency` and put it back in `apply/undo`. intentional?

sorry I made a mistake yesterday, I am fixing this changes

**Comment by danieldeidda** [comment]
travis is failing because I use std::to_string and std::stof which only works with c++11. It fails with:
1) EXTRA_BUILD_FLAGS="-DDISABLE_CERN_ROOT=1 -DSTIR_OPENMP:BOOL=OFF" CC=clang-5.0 CXX=clang++-5.0 

2) EXTRA_BUILD_FLAGS="-DDISABLE_CERN_ROOT=1 -DSTIR_OPENMP:BOOL=OFF" CC=gcc-5 CXX=g++-5

**Comment by KrisThielemans** [comment]
yes indeed. Please stick to pre-C++-11 until we get 4.0 out... `boost::format` etc. maybe you could insert links to the line numbers if you need suggestions.

**Comment by KrisThielemans** [comment]
superseded by #445

**Pull request closed without merging**
