### PR TITLE
Extract image executables: name change

### PR DESCRIPTION
**Pull request by rijobro**
I got confused between these two, so best to clear up the names.
extract_dynamic_images -> extract_single_images_from_dynamic_image
get_dynamic_images_from_parametric_images -> extract_dynamic_images_from_parametric_images

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Not sure about renaming `get_dynamic_images_from_parametric_images` to `extract_*`. For me, "extracting" is a simple function that gets some stuff out of some other stuff. This function actually computes the dynamic images from the kinetic model.

we could rename it to something better, but if we do, we'd have to check the `test_modelling.sh` script I presume.

**Comment by rijobro** [comment]
We can leave `get_dynamic_images_from_parametric_images` as it is, the main one was `extract_dynamic_images`, which implies that the output is dynamic images (obviously that's my fault since I created it...).

So leave `get_dynamic_images_from_parametric_images` as it is and change `extract_dynamic_images` to `extract_single_images_from_dynamic_image`. Is that ok with you?

**Comment by KrisThielemans** [comment]
sure

**Comment by rijobro** [comment]
done

**Comment by KrisThielemans** [comment]
release notes and users guide? (commit with `[ci skip]` in first line)

**Comment by KrisThielemans** [comment]
sorry. I notice this one. you used `extract_single_images_from_dynamic_images`. To me, `extract_single_images_from_dynamic_image` is more logical...

**Comment by rijobro** [comment]
done.

**Pull request merged**
