### PR TITLE
calibration factor is read from the interfile header. BinNormalisatio…

### PR DESCRIPTION
**Pull request by danieldeidda**
…n derived classes will need to check whether this has been read and if not read somewhere else

### CODE REVIEW

**Comment by danieldeidda** [comment]
travis error seems to say that calibartion factor is different in that check. Maybe connected to #809

**Comment by KrisThielemans** [comment]
I guess best to use "approx equal" checks for all floats in `ExamInfo::operator==`

**Comment by danieldeidda** [comment]
> 
> 
> I guess best to use "approx equal" checks for all floats in `ExamInfo::operator==`

But one is -1 and the other is something to the power of -38. Which I think means that calib_factor needs o be initialised somewhere

**Comment by danieldeidda** [comment]
This needs to set defaults for calibration factor

**Comment by KrisThielemans** [comment]
change https://github.com/UCL/STIR/blob/e3322df118ec0fd04a988839e3cef15b063f60e8/src/include/stir/ExamInfo.h#L133 to
use `(both calib factors <=0) || (abs(ratio -1) <= 1E-4)` or something like this.

I would move the implementation of `ExamInfo::operator==` to the .cxx

**Review by KrisThielemans — APPROVED** [review]

**Pull request merged**
