### PR TITLE
Convert image type

### PR DESCRIPTION
**Pull request by rijobro**
Convert any image file format to another supported by STIR. Give output filename, input filename and output file format parameter file.

### CODE REVIEW

**Comment by ashgillman** [comment]
Doesn't `stir_math` already do this?

**Comment by KrisThielemans** [comment]
Yes, `stir_math` does it, and can also be used for projection data (to get to Interfile only at present).

Can you create an entry in the FAQ instead?

**Comment by rijobro** [comment]
How about for dynamic and parametric images?

**Comment by KrisThielemans** [comment]
`stir_math` uses standard STIR IO for those as well. Its [usage message ](https://github.com/UCL/STIR/blob/e2f0bcb74af6bbf067785e07f58a8430faf3c64d/src/utilities/stir_math.cxx#L264) claims it can do dynamics and parametrics... should work (he says optimistically)

**Pull request closed without merging**
