### PR TITLE
Use FindPython, and improve GHA to use venv

### LINKED ISSUE #979: GHA: MacOS failure to import numpy
https://github.com/UCL/STIR/runs/4716700749?check_suite_focus=true#step:11:37
```
/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
swig/test/python/test_IO.py:14: in <module>
    from stir import *
../install/python/stir.py:15: in <module>
    from _stir import *
E   ImportError: numpy.core.multiarray failed to import
------------------------------- Captured stderr --------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/numpy/__init__.py", line 380, in <module>
    raise RuntimeError(msg)
```

More than likely due to version conflict between the `brew` Python and another one, see e.g. https://stackoverflow.com/questions/58342005/macos-python3-with-brew-error-on-import-cv2

### PR DESCRIPTION
**Pull request by KrisThielemans**
<strike>Fixes #979 </strike>
(but not just yet)

### CODE REVIEW

**Comment by KrisThielemans** [comment]
I think the underlying problem was actually that CMake found a different Python library from the one that was used at run-time. I've therefore now switched to `FindPython`. But now I get a different error (sigh)
```
  File "/usr/local/lib/python3.9/site-packages/numpy/__init__.py", line 380, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend.
If you compiled yourself, more information is available at:
https://numpy.org/doc/stable/user/building.html#accelerated-blas-lapack-libraries
Otherwise report this to the vendor that provided NumPy.
```
Some related info on this error:
https://trac-test.macports.org/ticket/61490 and
https://github.com/numpy/numpy/issues/20418. Those say that the error went away, but here it is again...

**Comment by KrisThielemans** [comment]
https://github.com/numpy/numpy/issues/15947#issuecomment-941601207 says to rebuild numpy make sure it doesn't use Accelerate but OpenBLAS. oh well

**Comment by KrisThielemans** [comment]
I can't rebuild `numpy`. I tried
```
python3 -m pip install --no-cache-dir --no-binary numpy numpy
```
and [now](https://github.com/UCL/STIR/runs/4967936204?check_suite_focus=true#step:4:120) get
```
RuntimeError: Setuptools version is '60.5.0', version < '60.0.0' is required. See pyproject.toml
```
@robbietuk maybe you can give some advice on how turn on MacOS these days

**Comment by robbietuk** [comment]
As mentioned here: (https://github.com/numpy/numpy/issues/20824#issuecomment-1013562608), you may want to try a venv?

**Comment by KrisThielemans** [comment]
so... i think I have finally created the virtualenv correctly. `python -c 'import numpy; print(numpy.pi); import numpy.core.multiarray` works, but `pytest` still fails with the Polyfit sanity test. https://github.com/UCL/STIR/runs/4977297464?check_suite_focus=true#step:11:74

Looks like I have to try with rebuilding numpy anyway.

madness

**Comment by KrisThielemans** [comment]
rebuilding `numpy` didn't help

**Comment by KrisThielemans** [comment]
I've cleaned-up the history and squashed all the GHA commits.

**Comment by KrisThielemans** [comment]
I tried one more time with [MacOS with some extra printout of Python libraries](https://github.com/UCL/STIR/runs/4990403805?check_suite_focus=true#step:6:170)
```
.... Python_LIBRARIES: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib
.... Python_INCLUDE_DIRS: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9
.... Python_NumPy_INCLUDE_DIRS: /Users/runner/work/STIR/STIR/my-env/lib/python3.9/site-packages/numpy/core/include
```
This looks all perfectly fine, So I have no idea what's going on.

I'll disable the MacOS Python check and merge.

**Pull request merged**
