### PR TITLE
Remove detector swapping when unlisting root

### PR DESCRIPTION
**Pull request by ludovicabrusaferri**
Removed swapping in https://github.com/UCL/STIR/blob/9be73d4615e4cd53a6fbc2abdd6ebf4e8f85e59d/src/listmode_buildblock/CListRecordROOT.cxx#L60 as it was unnecessary.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@NikEfth merging this PR will create conflicts for the TOF branch (sorry). Best to therefore merge master to the TOF branch just before and after merging this PR...

**Comment by NikEfth** [comment]
Sure no worries ...

**Comment by KrisThielemans** [comment]
@NikEfth this is ready for merging. Do you want to merge master to the TOF_branch first?

**Comment by KrisThielemans** [comment]
I'll merge now. @NikEfth, you can always do the merge to your TOF branch in 2 stages

**Comment by NikEfth** [comment]
Just got back.
Give me 20 mins.

**Comment by NikEfth** [comment]
done

**Pull request merged**
