### PR TITLE
add additional override

### PR DESCRIPTION
**Pull request by danieldeidda**
fixing #857

### CODE REVIEW

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
thanks. there are some others. e.g. https://travis-ci.com/github/UCL/STIR/jobs/500119597#L12227. do a search in that log on `override` I guess....

**Comment by danieldeidda** [comment]
> 
> 
> thanks. there are some others. e.g. https://travis-ci.com/github/UCL/STIR/jobs/500119597#L12227. do a search in that log on `override` I guess....

it reapeats the following many times:


/Users/travis/build/UCL/STIR/src/include/stir/recon_buildblock/BinNormalisationFromAttenuationImage.h:101:16: warning: 'apply' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]

  virtual void apply(RelatedViewgrams<float>& viewgrams) const;

i don't see other functions

**Comment by KrisThielemans** [comment]
ok great. Let's add that one in then. thanks!

**Comment by danieldeidda** [comment]
> 
> 
> ok great. Let's add that one in then. thanks!

Isn't that the one I put in ad1aec6?

**Comment by KrisThielemans** [comment]
looks like it, but it's not in this PR?

**Comment by danieldeidda** [comment]
> 
> 
> looks like it, but it's not in this PR?

yeah it's strange I have it in my fork but it does not look to be in master. I remember I did all the override in another pull request but I think that was merged

**Comment by KrisThielemans** [comment]
it cannot be on the branch that you generated this PR from, so I don't know what you mean with "not on my fork". In any case, please just do another commit on the relevant branch and push.

**Comment by danieldeidda** [comment]
> 
> 
>In any case, please just do another commit on the relevant branch and push.

Sorry I am confused: what should I commit? I thought have the "override" already. 
I can see the this was added here:
https://github.com/danieldeidda/STIR/commit/40387e9ac20a1384269fbf2296cd55dd98bed106

**Comment by KrisThielemans** [comment]
hmmm.

it is on your branch
https://github.com/danieldeidda/STIR/blob/issue857/src/include/stir/recon_buildblock/BinNormalisationFromAttenuationImage.h#L101

and your `master`
https://github.com/danieldeidda/STIR/blob/master/src/include/stir/recon_buildblock/BinNormalisationFromAttenuationImage.h#L101

but not on our `master`
https://github.com/UCL/STIR/blob/master/src/include/stir/recon_buildblock/BinNormalisationFromAttenuationImage.h#L101

With all this, it appears that github doesn't add it to this PR. I guess we don't quite know what they do in this situation...

I suppose the easiest way around this is for you to (assuming `upstream` is `UCL/STIR`)
```
git checkout upstream/master
git checkout -b override_fix
# make the changes again
git commit
# make a new PR
```
As your `master` and ours has diverged, I would recommend to sync them again
```
git checkout master
git reset --hard upstream/master
git push --force
```
maybe you want to keep your old master of course, which I guess should work via
```
git checkout master
git checkout -b old_master
# optionally push
git checkout master
git reset --hard upstream/master
git push --force
```

sorry, but best to fix this now, as otherwise it's going to hit us later.

**Pull request closed without merging**
