### PR TITLE
Compilerflag

### PR DESCRIPTION
**Pull request by casperdcl**
closes #64 as discussed in #63

### CODE REVIEW

**Comment by KrisThielemans** [comment]
not 100% sure about precedence rules in CMake.
do we mean
```
if(APPLE AND (${CMAKE_SYSTEM_NAME} MATCHES "Darwin" OR
                        ${CMAKE_CXX_COMPILER_ID} MATCHES "Clang"))
```
I'm not 100% sure if this is CLang specific, but I guess you researched it :-)

**Comment by KrisThielemans** [comment]
Both travis builds failed on OSX with clang with

> /usr/bin/ld: cannot find -lc++

(This is still without -std=c++11). It's not clear to me if this is because the Travis system has a missing library, or because the flags are incorrect. Sigh. @bathomas, would you be able to try this PR on your Mac?

**Comment by bathomas** [comment]
Hi,

Yes , this does work on my Mac:

macOS Sierra 10.12.2
clang-800.0.42.1

Ben

**Comment by KrisThielemans** [comment]
travis rebuild gave same problem. any ideas? (in 2017...)

**Comment by bathomas** [comment]
How about:

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++" CACHE STRING "compile flags" FORCE)

If you configure multiple times, you add multiple references to ‘-stdlib=libc++’ but I don’t think that matters.

Kind regards,

Ben

**Comment by casperdcl** [comment]
Can anyone replicate the problem on their own machines, or is just travis that's failing? If it's only travis I could re-add the line `if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then EXTRA_BUILD_FLAGS="$EXTRA_BUILD_FLAGS -stdlib=libc++"; fi` to travis' config.

**Comment by KrisThielemans** [comment]
I seem to have confused everyone by claiming that this build fails on OSX while it is actually failing on Linux with clang. To recall: error message is 
```
/usr/bin/ld: cannot find -lc++
```
Given that Travis claims that both clang and gcc work ok on OSX, I guess we need to change
```
if(APPLE AND ${CMAKE_SYSTEM_NAME} MATCHES "Darwin" OR
   ${CMAKE_CXX_COMPILER_ID} MATCHES "Clang")
```
to
```
if(${CMAKE_CXX_COMPILER_ID} MATCHES "AppleClang") OR
   (APPLE AND ${CMAKE_SYSTEM_NAME} MATCHES "Darwin" AND
    ${CMAKE_CXX_COMPILER_ID} MATCHES "Clang"))
```
(see also the [cmake Apple Clang policy](https://cmake.org/cmake/help/v3.9/policy/CMP0025.html#policy:CMP0025))

@casperdcl, what do you think?

By the way, why are we testing for `APPLE` and `CMAKE_SYSTEM_NAME``?

**Comment by KrisThielemans** [comment]
@casperdcl, could you either try to the above suggestion or give me write access to this PR (see https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)

**Comment by casperdcl** [comment]
@KrisThielemans you should already have write access. I've disabled and re-enabled edits from maintainers, perhaps it'll work now?

**Pull request merged**
