### PR TITLE
Merge release 4 to master

### PR DESCRIPTION
**Pull request by KrisThielemans**
This should bring master up-to-date again.

@rijobro I have updated the scatter bits, but haven't checked the rest. In particular the NiftyPET code needs your attention.

### CODE REVIEW

**Comment by rijobro** [comment]
Everything builds fine (including NiftyPET). All ctests and recon test pack are fine!

**Comment by KrisThielemans** [comment]
seems that #550 to enforce C++11 didn't work. One Travis job is failing accordingly. Also seen by @jafische  in  #507

**Comment by KrisThielemans** [comment]
Linux clang-5 job failed due to log-file exceeded. https://travis-ci.org/github/UCL/STIR/jobs/691726126. Main culprit is `auto_ptr<...> is deprecated`. This is despite
```
-- Using C++ version 11
...
-- Performing Test HAVE_STD_UNIQUE_PTR
-- Performing Test HAVE_STD_UNIQUE_PTR - Success
```
This is because we still check `BOOST_NO_CXX11_SMART_PTR` which is presumably not happy with the clang-5 implementation.
https://github.com/UCL/STIR/blob/a6cfddccb850df53c0e1ccb002f7d33985e098f1/src/include/stir/common.h#L172-L174

I'll disable this check

**Comment by KrisThielemans** [comment]
codacy failure is in the NiftyPET projector, but is minor so I'll ignore it.

**Pull request merged**
