### PR TITLE
require parallelproj 1.0

### LINKED ISSUE #1033: upgrade parallelproj requirement to 1.2
CMake doesn't use v1.0 as we currently require 0.8.

@gschramm says

> Since there are only TOF-related changes between 0.8 and 1.0
https://github.com/gschramm/parallelproj/releases/tag/v1.0.0
it should be safe to require to v1.0.

### PR DESCRIPTION
**Pull request by KrisThielemans**
Although previous versions of parallelproj will work for the no-TOF case anyway, it's easier to require the most recent version.

Fixes #1033

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@gschramm @markus-jehl maybe you could test this with CUDA? We'd need a self-hosted runner for GitHub Actions as far as I understand, but I wouldn't know where to get one...

**Comment by gschramm** [comment]
> @gschramm @markus-jehl maybe you could test this with CUDA? We'd need a self-hosted runner for GitHub Actions as far as I understand, but I wouldn't know where to get one...

For parallelproj, I am using [this](https://github.com/gschramm/parallelproj/blob/master/.github/workflows/Ubuntu.yml) github action to compile the CUDA lib (after installing CUDA). 
Compilation works, but obviously I cannot run the CUDA tests, since no physical CUDA GPU is present.

**Comment by markus-jehl** [comment]
I can certainly test it manually on my machine.

**Comment by KrisThielemans** [comment]
This is working fine now. @markus-jehl let me know if you plan to test tomorrow. if not, I'll just merge.

**Comment by markus-jehl** [comment]
I ran into some problems with building parallelproj 1.2, so wasn‘t able to test it yet unfortunately. Will try to get it working, but that won‘t happen before 3.1.2023!

**Comment by KrisThielemans** [comment]
@markus-jehl any chance you can try this today? I'd like to merge this asap to get 5.1.0 out of the door. if you cannot, I'd be happy to merge it now chances are quite high it will work, and we can always do a bug fix later :-)

**Comment by markus-jehl** [comment]
Sorry, forgot to write. I tried it yesterday with parallelproj 1.2.9 and everything works fine (had to build parallelproj with gcc in the end, because clang no longer seems to work).

**Comment by gschramm** [comment]
Hi Markus,
there was indeed a clang building issue with 1.2.9, but this issue should be resolved in 1.2.10 that is already on conda-forge. Can you double-check with clang?

Georg

**Comment by markus-jehl** [comment]
Hi Georg,
It still fails, unfortunately. I also saw an issue with the math library linking when trying to get the build working, but the real issue is that something internal still seems to be calling gcc. But I haven't managed to work out where this is happening. This is the output I get from the build:
[  8%] Building CUDA object cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o
[  8%] Building C object c/CMakeFiles/parallelproj_c.dir/src/joseph3d_back.c.o
[ 17%] Building CUDA object cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_tof_lm_cuda.cu.o
[ 34%] Building CUDA object cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_tof_sino_cuda.cu.o
[ 34%] Building C object c/CMakeFiles/parallelproj_c.dir/src/joseph3d_fwd.c.o
[ 34%] Building C object c/CMakeFiles/parallelproj_c.dir/src/joseph3d_back_tof_sino.c.o
[ 34%] Building C object c/CMakeFiles/parallelproj_c.dir/src/joseph3d_back_tof_lm.c.o
gcc: error: unrecognized command-line option '-fopenmp=libomp'; did you mean '-fopenmp-simd'?
[ 43%] Building CUDA object cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_fwd_cuda.cu.o
[ 43%] Building C object c/CMakeFiles/parallelproj_c.dir/src/joseph3d_fwd_tof_lm.c.o
gmake[2]: *** [cuda/CMakeFiles/parallelproj_cuda.dir/build.make:76: cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o] Error 1
gcc: error: unrecognized command-line option '-fopenmp=libomp'; did you mean '-fopenmp-simd'?
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [cuda/CMakeFiles/parallelproj_cuda.dir/build.make:90: cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_tof_lm_cuda.cu.o] Error 1
[ 52%] Building CUDA object cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_fwd_tof_lm_cuda.cu.o
[ 52%] Building C object c/CMakeFiles/parallelproj_c.dir/src/joseph3d_fwd_tof_sino.c.o
[ 52%] Building CUDA object cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_fwd_tof_sino_cuda.cu.o
[ 65%] Building C object c/CMakeFiles/parallelproj_c.dir/src/ray_cube_intersection.c.o
[ 65%] Building CUDA object cuda/CMakeFiles/parallelproj_cuda.dir/src/projector_kernels.cu.o
[ 65%] Building C object c/CMakeFiles/parallelproj_c.dir/src/tof_utils.c.o
gcc: error: unrecognized command-line option '-fopenmp=libomp'; did you mean '-fopenmp-simd'?
gmake[2]: *** [cuda/CMakeFiles/parallelproj_cuda.dir/build.make:104: cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_tof_sino_cuda.cu.o] Error 1
gcc: error: unrecognized command-line option '-fopenmp=libomp'; did you mean '-fopenmp-simd'?
gcc: error: unrecognized command-line option '-fopenmp=libomp'; did you mean '-fopenmp-simd'?
gmake[2]: *** [cuda/CMakeFiles/parallelproj_cuda.dir/build.make:118: cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_fwd_cuda.cu.o] Error 1
gcc: error: unrecognized command-line option '-fopenmp=libomp'; did you mean '-fopenmp-simd'?
gmake[2]: *** [cuda/CMakeFiles/parallelproj_cuda.dir/build.make:146: cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_fwd_tof_sino_cuda.cu.o] Error 1
gmake[2]: *** [cuda/CMakeFiles/parallelproj_cuda.dir/build.make:132: cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_fwd_tof_lm_cuda.cu.o] Error 1
gcc: error: unrecognized command-line option '-fopenmp=libomp'; did you mean '-fopenmp-simd'?
gmake[2]: *** [cuda/CMakeFiles/parallelproj_cuda.dir/build.make:160: cuda/CMakeFiles/parallelproj_cuda.dir/src/projector_kernels.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:985: cuda/CMakeFiles/parallelproj_cuda.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 69%] Linking C shared library libparallelproj_c.so
[ 69%] Built target parallelproj_c
gmake: *** [Makefile:146: all] Error 2

**Comment by markus-jehl** [comment]
Option 1 didn't work either:
[ 52%] Building CUDA object cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o
cd /workspace/public-fork/parallelproj-1.2/build/cuda && /usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -Dparallelproj_cuda_EXPORTS -I/workspace/public-fork/parallelproj-1.2/cuda/include -Xcompiler=-fopenmp=libomp --generate-code=arch=compute_52,code=[compute_52,sm_52] -Xcompiler=-fPIC -std=c++14 -MD -MT cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o -MF CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o.d -x cu -dc /workspace/public-fork/parallelproj-1.2/cuda/src/joseph3d_back_cuda.cu -o CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o

With parallelproj 0.8 the clang build was still working, but this seems to be because the OpenMP flag was not set back then:
[ 56%] Building CUDA object cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o
cd /workspace/public-fork/parallelproj-0.8/build/cuda && /usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -Dparallelproj_cuda_EXPORTS -I/workspace/public-fork/parallelproj-0.8/cuda/include -O3 -DNDEBUG --generate-code=arch=compute_52,code=[compute_52,sm_52] -Xcompiler=-fPIC -std=c++14 -MD -MT cuda/CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o -MF CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o.d -x cu -dc /workspace/public-fork/parallelproj-0.8/cuda/src/joseph3d_back_cuda.cu -o CMakeFiles/parallelproj_cuda.dir/src/joseph3d_back_cuda.cu.o

I also tried option 2 with clang++ version 14.0.0, and it failed already in the cmake generation phase (from the sounds of it because clang doesn't support the required CUDA version):
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCUDACompiler.cmake:56 (message):
  The CUDA compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /workspace/public-fork/parallelproj-1.2/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_c00c8/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_c00c8.dir/build.make CMakeFiles/cmTC_c00c8.dir/build
    gmake[1]: Entering directory '/workspace/public-fork/parallelproj-1.2/build/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_c00c8.dir/main.cu.o
    /usr/bin/clang++      -c /workspace/public-fork/parallelproj-1.2/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_c00c8.dir/main.cu.o
    clang: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
    In file included from <built-in>:1:
    In file included from /usr/lib/llvm-14/lib/clang/14.0.0/include/__clang_cuda_runtime_wrapper.h:365:
    /usr/lib/llvm-14/lib/clang/14.0.0/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture'
                texture<__DataT, __TexT, cudaReadModeNormalizedFloat> __handle,
                ^
    /usr/lib/llvm-14/lib/clang/14.0.0/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture'
                texture<__DataT, __TexT, cudaReadModeElementType> __handle,
                ^
    2 errors generated when compiling for sm_35.
    gmake[1]: *** [CMakeFiles/cmTC_c00c8.dir/build.make:78: CMakeFiles/cmTC_c00c8.dir/main.cu.o] Error 1
    gmake[1]: Leaving directory '/workspace/public-fork/parallelproj-1.2/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_c00c8/fast] Error 2

**Comment by KrisThielemans** [comment]
I feel this discussion should happen on the parallelproj github really. it's going to be a bit lost here.

Just one comment, it is generally recommended to do
```
env CC=bla CXX=bla cmake whateveroptions
```
as opposed to setting `-DCMAKE_C_COMPILER` and `-DCMAKE_CXX_COMPILER` (or at least, it used to be). Also, it needs to be done in a clean build directory, as these variables cannot be changed once it has run.

**Comment by markus-jehl** [comment]
True! I have these two variables set to clang on my docker image by default. Happy to take the discussion across to the parallelproj github, but also happy to simply build parallelproj with gcc for the time being ;-)

**Comment by KrisThielemans** [comment]
I've changed the required version back to 1.0 for now. Once we merge to TOF, we can require 1.2 (not sure if we can require 1.2.9, this depends on how parallelproj handles versions).

I will merge this if the non-Debug builds pass (and find parallelproj)

**Comment by gschramm** [comment]
> I've changed the required version back to 1.0 for now. Once we merge to TOF, we can require 1.2 (not sure if we can require 1.2.9, this depends on how parallelproj handles versions).
> 
> I will merge this if the non-Debug builds pass (and find parallelproj)

I am using semantic versioning. So featurewise 1.2.9 is the same as 1.2.x and all 1.x versions have the same API

**Comment by gschramm** [comment]
> True! I have these two variables set to clang on my docker image by default. Happy to take the discussion across to the parallelproj github, but also happy to simply build parallelproj with gcc for the time being ;-)

Both fine for me. I will also try to build with clang and nvcc in the next days on my (physical) system.

**Pull request merged**
