### PR TITLE
Deprecated function fixes

### PR DESCRIPTION
**Pull request by robbietuk**
Addesses *some* of #856

### CODE REVIEW

**Comment by robbietuk** [comment]
With `BUILD_TESTING=OFF` I can compile.

https://github.com/UCL/STIR/blob/4c0b7637cb33ea7d11699c084b160f433ee96f45/src/test/test_Array.cxx#L578 I cant figure out how work. Any idea on a solution @KrisThielemans?

**Comment by KrisThielemans** [comment]
```
in_place_apply_function(test3ter, std::bind(plus<float>(), std::placeholder::_1, 4.F));
```
I guess

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
need to `#include <functional>` (seems it wasn't there even if it had to be)

**Comment by KrisThielemans** [comment]
Feel like getting rid of `boost/bind` in `GeneralisedPoissonNoiseGenerator.h` as well? You know now how.

**Review by KrisThielemans — APPROVED** [review]

**Pull request merged**
