### PR TITLE
Small fixes to listmode recon

### PR DESCRIPTION
**Pull request by NikEfth**
* Set has_add from par file
* Use cache from par file

### CODE REVIEW

**Comment by KrisThielemans** [comment]
```
/home/runner/work/STIR/STIR/src/recon_buildblock/PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin.cxx:352:7: error: use of undeclared identifier 'has_add'
      has_add = true;
```

**Comment by KrisThielemans** [comment]
First 2 jobs fail with
```
=== Reconstruct listmode data without cache
Error: Process completed with exit code 134.
```
The MacOS job will always fail #1036. I guess I should disable it such that we can get at the log files (it doesn't seem to store them if we cancel the workflow).

**Comment by NikEfth** [comment]
I am trying to find what error 134 is, but it doesn't look common. 
I have already tried this PR in 2 machines and looks good on myside.

**Comment by KrisThielemans** [comment]
I ran this on mine and see several problems in OSMAPOSL_test_lm_1.log
```
WARNING: KeyParser warning: unrecognized keyword: projector pair type
WARNING: KeyParser warning: unrecognized keyword: projector pair using matrix parameters
WARNING: KeyParser warning: unrecognized keyword: end projector pair using matrix parameters
```
indicate problems with the .par file which should be fixed, but doesn't cause failures. but then
```
WARNING: Please set the max cache size for the listmode file
INFO: Reading cache from disk...
ERROR: FilePath: Cannot access /home/sirfuser/devel/STIR2/recon_test_pack/my_CACHE00.bin.
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
```
so I guess you ran with an existing cache file and therefore didn't notice this error.

another problem in the test script is that 3 calls to `compare_image` write to the same log file

**Comment by NikEfth** [comment]
I am looking into this. Indeed my tests were with an already calculated cache. But I am also preparing the exercises, and that works.

**Comment by NikEfth** [comment]
Hopefully, this will do the trick.

**Comment by KrisThielemans** [comment]
looks like it. great.

can you please fix the test script and par file as well (delete the myCACHE.bin at the start for instance)

**Comment by KrisThielemans** [comment]
thanks. I'll merge, but please do another PR to fix the .par file

**Comment by KrisThielemans** [comment]
Merged via fb971fe51939c3c91ed7e211e9c714f6c97e10a1 (squashed listmode-related commits). I've kept the GHA commit separately.

**Pull request closed without merging**
