### PR TITLE
Examinfoequal

### PR DESCRIPTION
**Pull request by danieldeidda**
Modify  ExamInfo == operator. Checks all floats are equal up to a limit

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Hi Daniel!

I think you are implementing this worngly, you sould `abs(var1-var2)<=eps`.

Example of why:

seconds_since_1970 now: 1618485350
seconds_since_1970 tomorrow: 1618571851

seconds_since_1970_now/seconds_since_1970_tomorrow-1.)= -0.00005344279

**Comment by danieldeidda** [comment]
> 
> 
> Hi Daniel!
> 
> I think this way of comparing can have some bugs, you should `abs(var1-var2)<=eps`.
> 
> Example of why:
> 
> seconds_since_1970 now: 1618485350
> seconds_since_1970 tomorrow: 1618571851
> 
> `(1618485350/1618571851-1.)= -0.00005344279 `
> 
>     * is negative, meaning if the difference was higher, you may get a large negative number. In any case, this is enough to pass the check, regardless of the number.
> 
>     * is below tolerance in absolute terms, with an entire day of difference, so it should not be.
> 
>     * If they are `int` (I think they are?) the division will be rounded, and can pass the check with a `-1`

Well spotted thanks!

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
sadly, these will fail horribly when they the denominator is zero,
as we know what the units are for these things, I'd favour an absolute comparison
```
abs(this->up_energy_thres-p1.up_energy_thres ) > 1 /* keV*/
...
abs(this->start_time_in_secs_since_1970-p1.start_time_in_secs_since_1970) > .5 /* sec */
```

**Comment by KrisThielemans** [comment]
I would also modify `parameter_info()` like in
```c++
 s << "Scan start time: " << std::fixed << std::setprecision(12) <<this->start_time_in_secs_since_1970
   << std::setprecision(5) // reset for further floats
```

**Review by KrisThielemans — APPROVED** [review]
thanks. did you try and print if it looks ok (e.g. with `list_projdata_info --all`)?

**Comment by danieldeidda** [comment]
> 
> 
> thanks. did you try and print if it looks ok (e.g. with `list_projdata_info --all`)?

Yes:

Modality: nucmed
Calibration Factor: 1.000000000000
Radionuclide: ^90^Yttrium
Patient position: unknown
Scan start time: 0.000000000000
Time frame start - end (duration), all in secs: 0.00000 - 7200.00000 (7200.00000)
number of energy windows:=1
energy window lower level[1] := -1.00000
energy window upper level[1] := -1.00000
ProjDataInfoCylindricalArcCorr :=

**Comment by KrisThielemans** [comment]
ok, seems like `setprecision` now gives "digits after the dot" (I guess because of the `fixed`), so arguably we could use `setprecision(1)` or so.

if you do that, take the opportunity to update the copyright header, but commit with `ci skip`

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
need to include `<iomanip>`

**Comment by danieldeidda** [comment]
> 
> 
> ok, seems like `setprecision` now gives "digits after the dot" (I guess because of the `fixed`), so arguably we could use `setprecision(1)` or so.

1 instead of 12? or instead of 5?

**Comment by KrisThielemans** [comment]
> 1 instead of 12? or instead of 5?

I guess can just be 1 for all of them (after the calib factor). no?

**Review by KrisThielemans — APPROVED** [review]

**Comment by KrisThielemans** [comment]
Thanks. By the way, it has to be `[ci skip]`, not `[ci-skip]`...

Waiting for Travis and Appveyor

**Comment by danieldeidda** [comment]
> 
> 
> Thanks. By the way, it has to be `[ci skip]`, not `[ci-skip]`...
> 
> Waiting for Travis and Appveyor

ops sorry :D

**Comment by KrisThielemans** [comment]
All well. I've cancelled the Appveyor after 2 succesful builds. Merging

**Pull request merged**
