### PR TITLE
release_4 to master

### PR DESCRIPTION
**Pull request by robbietuk**
Can we update master with release_4? I need some seperate functionality that is in both branches.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
can you resolve the conflict please?

**Comment by robbietuk** [comment]
I don't have write access so I can't unfortunately.

**Comment by KrisThielemans** [comment]
It's your pr? Anyway. I'll have a look later

**Comment by KrisThielemans** [comment]
not sure what you did here, but next time, do the merge locally in a new branch, and make a PR from that. Then you can resolve conflicts to your hearts desire.

**Comment by KrisThielemans** [comment]
Closing in favour of #711

**Comment by robbietuk** [comment]
I should have done that yes. The PR was from UCL/release_4 to UCL/master. I didn't realise I would not have the permissions to resolve the conflicts sorry.

**Pull request closed without merging**
