### PR TITLE
Add test priors 2

### PR DESCRIPTION
**Pull request by robbietuk**
This PR is to replace and expand upon that of #519. 

Addresses #153

- [x] add Logcosh #716 
- [ ] consider adding Hessian test
- [ ] consider adding surrogate test

### CODE REVIEW

**Comment by robbietuk** [comment]
PLS will fail because of edge artefacts. Here is a difference image. PLS uses a uniform 1's anatomical image and the same randomised densitity as QP and RDP
image

**Comment by robbietuk** [comment]
I believe PLS is failing at the (max) edge because of continue statements in the directional gradient computation https://github.com/UCL/STIR/blob/7b4c27470ad175a80f29e9aabe945b6831a4f159/src/recon_buildblock/PLSPrior.cxx#L318-L333
The solution to this is not obvious.

**Comment by KrisThielemans** [comment]
@robbietuk, what about disabling the PLS test for now, adding logcosh and merging this PR?

**Comment by robbietuk** [comment]
Yes, I think we also expand the testing for RDP and logcosh priors to have more than one evaluation with different `gamma`(RDP)/`scalar`(logcosh) values. We didn't spot the logcosh error regarding the value compuation when the input is large for a couple of weeks.

Ill get on this shortly, did you want it for release4.1?

**Comment by robbietuk** [comment]
`test_priors` passes on my machine (waiting on Travis to confirm). This PR needs to be followed up with a further issue relating to additional tests for other methods but these should wait until the mess with the priors code has been cleaned up.

**Review by KrisThielemans — APPROVED** [review]

**Pull request merged**
