### PR TITLE
Fix of the aforementioned bug.

### PR DESCRIPTION
**Pull request by NikEfth**
Fix for bug #54

### CODE REVIEW

**Comment by KrisThielemans** [comment]
this will be a problem for every derived class. It's another example of adding a member to the abstract class which creates trouble.

I guess best resolution is to move this implementation with an error into CListModeData as the default, state clearly in the doxygen that the default just throws an error and not require the derived class to implement it.

**Comment by NikEfth** [comment]
Indeed, this is far better.

**Comment by KrisThielemans** [comment]
great. add a line to the release notes please. then I accept as squashed commit?

**Comment by NikEfth** [comment]
Done. 
Sure fine with me

**Pull request merged**
