### PR TITLE
Extend VoxelsOnCartesianGrid to include sapyb and test

### PR DESCRIPTION
**Pull request by Robert-PrescientImaging**
Fixes part of #863

### CODE REVIEW

**Comment by Robert-PrescientImaging** [comment]
I have also tried to add support for `+=` and `-=` via the following
```
    // Define the __iadd__ method to support +=
    stir::VoxelsOnCartesianGrid<elemT>& operator+=(const stir::VoxelsOnCartesianGrid<elemT>& other) 
    {
      $self->sapyb(1.0f, other, 1.0f);
      return *$self;
    }
    
    // Define the __iadd__ method to support +=
    stir::VoxelsOnCartesianGrid<elemT>& operator-=(const stir::VoxelsOnCartesianGrid<elemT>& other) 
    {
      $self->sapyb(1.0f, other, -1.0f);
      return *$self;
    }
```
but it returns a pointer to the wrong data. I don't understand swig... 😞

**Comment by Robert-PrescientImaging** [comment]
With the swig:
```
    void __iadd__(const Array<3, float>& y)
    { 
      $self->sapyb(1.0f,y,1.0f); 
    }
```
I get get the following python test working, but not the commented out `image += image` (returns `None` type).
```
    image.fill(test_value)
    # image += image
    image.__iadd__(image)
    assert image.find_max()==pytest.approx(2*test_value)
    assert image.find_min()==pytest.approx(2*test_value)
```

**Comment by Robert-PrescientImaging** [comment]
I have also tried this approach, with the `%extend` scope:
```
    // Define += operator
    VoxelsOnCartesianGrid<float>& operator+=(VoxelsOnCartesianGrid<float>& y)
    { 
      self->sapyb(1.0f, y, 1.0f);
      return *self;
    }
```
but this returns a different pointer than that of `image`

**Comment by KrisThielemans** [comment]
I think I'd first try to get this to work on the Arrays. Probably 
```
%extend Array {
 stir::Array& operator+=(const stir::Array& other) 
{
  $self->operator+=(other);
  return $self;
}
}

```
could do the trick. If not, doing the same but with 
%extend Array {
 stir::Array& __iadd__(const stir::Array& other) 
{
 ...
}
}
```
could work.

Question is then if it transports it to `VoxelsOnCartesianGrid`. If not, can add the same lines there. (which then I'd do via a macro of course)

**Comment by Robert-PrescientImaging** [comment]
I cannot get any of the addition or in place addition to work on Arrays either, debugging is painful. I am happy to just add the already committed `sapyb` methodology to the `VoxelsOnCartesianGrid`, unless you want to try to fix the underlying issue with it not inheriting this property from `Array`?

**Pull request merged**
