### PR TITLE
compute..Hessian.par file error fix

### PR DESCRIPTION
**Pull request by robbietuk**
Addresses #802

### CODE REVIEW

**Comment by KrisThielemans** [comment]
rest of the parameters ok?

**Comment by robbietuk** [comment]
I can't see any further problems 😄

**Comment by robbietuk** [comment]
Hold on, I need to check one or two more things.

**Comment by robbietuk** [comment]
Okay, all okay. I retested the script and the output images with a restricted FOV have a large value ring around the edge of the FOV. I wanted to quickly investigate this but it should be okay. Turning the restricted FOV off removes this ring. This is therefore a consequence of projector sensitivity?
image

**Comment by KrisThielemans** [comment]
sure. it's `P' (1/y) P 1`, so near the edge of the FOV, `y` gets small, so the row-sum gets large (only well-defined with background term of course). And the final backprojection will only update voxels that are with the circular FOV.

**Pull request merged**
