### PR TITLE
 adding Ge68 to radionuclide database

### PR DESCRIPTION
**Pull request by danieldeidda**

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@paulclegg can you check if these values are consistent with what Siemens has in their headers? (in particula rthe branching ratio).

@danieldeidda I cannot remember if we have any tests that check if the json files are well-formed. do You?

**Comment by danieldeidda** [comment]
We have this:
https://github.com/danieldeidda/STIR/blob/addGe68/src/test/test_radionuclide.cxx

**Comment by PaulClegg** [comment]
Hi both,

They are similar but not identical:


Kings – from dcm header



isotope name :=C-11

isotope gamma halflife (sec) :=1223

isotope branching factor :=1

radiopharmaceutical :=Acetat





Kings – from Scatter / Randoms / Acq



radionuclide name[1] := ^11^Carbon

radionuclide halflife (sec)[1] := 1221.66

radionuclide branching factor[1] := 0.9975



UoE – from dcm header



isotope name :=Ga-68

isotope gamma halflife (sec) :=4062.6

isotope branching factor :=0.8891

radiopharmaceutical :=FAPI





UoE – from Scatter / Randoms / Acq



radionuclide name[1] := ^68^Gallium

radionuclide halflife (sec)[1] := 4069.8

radionuclide branching factor[1] := 0.8768

All the best,
Paul.


Prof Paul Clegg
School of Physics and Astronomy
University of Edinburgh
Peter Guthrie Tait Road
Edinburgh EH9 3FD, UK

tel. +44 (0)131 650 5295
________________________________

**Comment by KrisThielemans** [comment]
Thanks @PaulClegg but you had a Ge68 as well?

@danieldeidda got the other numbers from some approved reference. Who knows where Siemens got their data from. At the moment, we use our numbers and ignore the values in the header. Maybe this is worth making explicit somewhere.

**Comment by danieldeidda** [comment]
Hi, Yes the numbers in STIR are from standardised measurements.  The tables are from here :http://www.lnhb.fr/accueil/donnees-nucleaires/donnees-nucleaires-tableau/

for Ge68: http://www.lnhb.fr/nuclides/Ge-68_tables.pdf

**Comment by PaulClegg** [comment]
Hi Kris,

Yes - Ge-68 was used for the Kings normalisation scan.

Neither halflife nor branching ratio appear in the relevant dcm file.

I am not seeing anything about Ge in the .hs files produced by SIRF.

All the best,
Paul.


Prof Paul Clegg
School of Physics and Astronomy
University of Edinburgh
Peter Guthrie Tait Road
Edinburgh EH9 3FD, UK

tel. +44 (0)131 650 5295
________________________________

**Comment by KrisThielemans** [comment]
@PaulClegg I remember it was in the Siemens .s.hdr. no?

**Comment by KrisThielemans** [comment]
@danieldeidda as we cannot add a comment to JSON files, what about adding a field "data-origin" specifying the URLs that you have. I think this can be done without any code changes, but might need a change in the doc. (I can't remember if it has to be present or not). Otherwise we will forget...

**Comment by danieldeidda** [comment]
I seem to remember we had put the link in the documentation, but maybe not. Yes JSON does not seem to allow comments

**Comment by PaulClegg** [comment]
Hi Kris,

The UoE NEMA scan is already in sinograms - but the radionuclide here was:

isotope name:=F-18
isotope gamma halflife (sec):=6586.2
isotope branching factor:=0.9673
radiopharmaceutical:=Flutemetamol

I am still trying to get team-Edinburgh to decompress the sinograms for me. The numbers above are in both the dcm and the s.dhr.

All the best,
Paul.


Prof Paul Clegg
School of Physics and Astronomy
University of Edinburgh
Peter Guthrie Tait Road
Edinburgh EH9 3FD, UK

tel. +44 (0)131 650 5295
________________________________

**Comment by KrisThielemans** [comment]
hmmm. you did show me a Ge-68 header...

**Comment by PaulClegg** [comment]
Hi Kris,

I'm not sure what that was. Both the cardiology study and the NEMA phantom study have normalisation measurements carried out with Ge-68. I am not seeing any radionuclide characteristics in any of the files associated with these.

If I stumble onto something - I will let you know!

All the best,
Paul.


Prof Paul Clegg
School of Physics and Astronomy
University of Edinburgh
Peter Guthrie Tait Road
Edinburgh EH9 3FD, UK

tel. +44 (0)131 650 5295
________________________________

**Pull request merged**
