### PR TITLE
Issue/1101 adapt safir format for positrigo

### PR DESCRIPTION
**Pull request by markus-jehl**

### CODE REVIEW

**Comment by markus-jehl** [comment]
Still need to work out how to support this format also for executables and .par files in Python.

**Comment by markus-jehl** [comment]
> 

This is now working.

**Comment by KrisThielemans** [comment]
Appveyor job failure is due to time-out

**Comment by KrisThielemans** [comment]
@markus-jehl can you add something to `release-5.1.htm`? It's in principle a backwards-breaking change but terribly unlikely anyone will be instantiating `SAFIRCListmodeInputFileFormat` etc explicitly, so I'm happy to include it in that release. But do state it's a backwards incompatible change.

**Comment by KrisThielemans** [comment]
there seems to be a conflict in the release notes. can you merge master onto here and resolve?

ok to squash-merge then?

**Comment by markus-jehl** [comment]
Done. Squash-merge is fine by me!

**Pull request merged**
