### PR TITLE
Closes #177, closes #187

### LINKED ISSUE #177: bug in CreateTailMaskFromACFs::set_defaults
@NikEfth, `set_defaults` sets local variables as opposed to the class members.

### LINKED ISSUE #187: Bug on Scanner creation
The pointer to the Scanner is local, L919:942
```
      if (EnergyResolution > -1 && ReferenceEnergy > -1)
        Scanner* scanner_ptr =
            new Scanner(type, string_list(name),
                        num_detectors_per_ring,  NoRings,
                        NoBins, NoBins,
                        InnerRingRadius, AverageDepthOfInteraction,
                        RingSpacing, BinSize,intrTilt*float(_PI)/180,
                        AxialBlocksPerBucket,TransBlocksPerBucket,
                        AxialCrystalsPerBlock,TransaxialCrystalsPerBlock,
                        AxialCrstalsPerSinglesUnit, TransaxialCrystalsPerSinglesUnit,
                        num_detector_layers,
                        EnergyResolution,
                        ReferenceEnergy );
      else
        Scanner* scanner_ptr =
            new Scanner(type, string_list(name),
                        num_detectors_per_ring,  NoRings,
                        NoBins, NoBins,
                        InnerRingRadius, AverageDepthOfInteraction,
                        RingSpacing, BinSize,intrTilt*float(_PI)/180,
                        AxialBlocksPerBucket,TransBlocksPerBucket,
                        AxialCrystalsPerBlock,TransaxialCrystalsPerBlock,
                        AxialCrstalsPerSinglesUnit, TransaxialCrystalsPerSinglesUnit,
                        num_detector_layers);
```

### PR DESCRIPTION
**Pull request by NikEfth**
This PR closes #177 and closes #187.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Looks good! I guess we have to wait for Travis.

By the way, for future, I prefer commit messages that explain the change and not just refer to a github issue. (if we ever move from github, all those # will become meaningless...)

**Comment by KrisThielemans** [comment]
oh, and see https://help.github.com/articles/closing-issues-using-keywords/ for the correct wording(one per issue) to auto-close an issue

**Comment by NikEfth** [comment]
Would you like me to repeat the PR? It is no trouble at all.

**Comment by KrisThielemans** [comment]
no, thanks. I'll just squash. should allow me to change the commit message.

**Pull request merged**
