### PR TITLE
Number of time frames in wrong position in interfile header fix

### PR DESCRIPTION
**Pull request by ALEXJAZZ008008**
Moved the method call "write_interfile_time_frame_definitions(output_header, exam_info);" to be in the correct place when creating interfile headers.

This is to fix issue #320: Number of time frames in wrong position in interfile header

### CODE REVIEW

**Comment by KrisThielemans** [comment]
sadly fails with "ERROR: KeyParser: the list corresponding to the keyword "image scaling factor" has to be resized to size 2. This means you have a problem in the keyword values." Not 100% sure why. Would have to compare the interfile header written now with what we had before we changed the location of the time frame defs keyword.

**Comment by KrisThielemans** [comment]
please paste a new .hv header here.

#320 is really due to a problem in medcon (as used by Amide). Your fix might help amide, but it breaks STIR reading of the header.

**Comment by ALEXJAZZ008008** [comment]
!INTERFILE  :=
!imaging modality := PT
!version of keys := STIR3.0
name of data file := ImageData1553019963368335.v
!GENERAL DATA :=
patient orientation := head_in
patient rotation := prone
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Image
process status := Reconstructed
!number format := float
!number of bytes per pixel := 4
number of dimensions := 3
matrix axis label [1] := x
!matrix size [1] := 125
scaling factor (mm/pixel) [1] := 3.1088
matrix axis label [2] := y
!matrix size [2] := 125
scaling factor (mm/pixel) [2] := 3.1088
matrix axis label [3] := z
!matrix size [3] := 31
scaling factor (mm/pixel) [3] := 6.75
number of time frames := 1
first pixel offset (mm) [1] := -192.746
first pixel offset (mm) [2] := -192.746
first pixel offset (mm) [3] := 0
!END OF INTERFILE :=

**Comment by KrisThielemans** [comment]
clarification. The error is in `test_IO_ParametricDiscretisedDensity.*`

**Comment by KrisThielemans** [comment]
The reason this fails is actually due to a bug in the Interfile reading code (fix coming up). However, the order of the keywords was a bit strange. I've commited a change to put them all together again.

**Pull request merged**
