### PR TITLE
CListEvent changes for BlocksOnCylindrical

### PR DESCRIPTION
**Pull request by VietAnhDao**
1. Adjusted CListEvent for root files.
 
- Stored ProjDataInfo instead of ProjDataInfoCylindrical.

- Downcast ProjDataInfo to correct geometry when needed.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
It seems this breaks the listmode recon, `run_test_listmode_recon.sh` crashes out with a segfault. https://github.com/UCL/STIR/runs/5259249760?check_suite_focus=true#step:9:321

**Comment by KrisThielemans** [comment]
@VietAnhDao I believe I fixed the problem. Unfortunately I cannot write to your branch. Normally with a PR, maintainers can write to the branch (I believe that's the default in GitHub), but possibly it doesn't work here because you did this work on your `master`. Never a good idea...

I've created #994 where I've squashed some of your commits, and added mine on top. Have a look. Could you check if that works for you?

By the way, as I squashed your commits, more than likely you'll have trouble with your `master` later. I'd recommended making it identical to `UCL/master` again once this is merged. See e.g. https://stackoverflow.com/a/1628334/3467846

**Comment by VietAnhDao** [comment]
@KrisThielemans works for me 👍. PR close.

**Comment by KrisThielemans** [comment]
sorry, did you mean that  #994 works for you?

**Comment by VietAnhDao** [comment]
sorry about the ambiguous wording of "works" but yes just tested the build and the conversion definitely works for 'Cylindrical' and seems to work for 'BlocksOnCylindrical'. The main take away is:

- The sinogram of a point source has the characteristic kink instead of a smooth sine wave(pic attached).
- The output interfile says 'Cylindrical'... very 

Btw should we move this conversation to #994 ?

test_root_point_source

**Comment by KrisThielemans** [comment]
Yes please. Comment on the new PR and complete the sentence in the 2nd bullet please

**Pull request closed without merging**
