### PR TITLE
Reverting a change that broke the blocks on cylindrical geometry.

### PR DESCRIPTION
**Pull request by markus-jehl**
## Changes in this pull request
Reverted a part of commit: https://github.com/UCL/STIR/commit/42bf1e98e1cfb3c7fae131fb8590b439ff07068c

## Related issues
fixes https://github.com/UCL/STIR/issues/1390

## Checklist before requesting a review

  - [] I have performed a self-review of my code
  - [] I have added docstrings/doxygen in line with the guidance in the developer guide
  - [] I have implemented unit tests that cover any new or modified functionality (if applicable)
  - [] The code builds and runs on my machine
  - [] `documentation/release_XXX.md` has been updated with any functionality change (if applicable)

### CODE REVIEW

**Comment by markus-jehl** [comment]
@danieldeidda @KrisThielemans This is ready now from my side. The detector coordinate test could clearly be improved since we didn't notice the wrong geometry, but the python plotting tool shows that it is now correct.

**Comment by KrisThielemans** [comment]
Thanks @markus-jehl. Could you add a plot here for future reference? Please also modify the release_6.2.htm.

@danieldeidda please check.

**Comment by markus-jehl** [comment]
image

**Comment by danieldeidda** [comment]
having a look now

**Comment by danieldeidda** [comment]
just for my understanding could it be possible to see the plot showing the wrong geometry

**Comment by KrisThielemans** [comment]
See https://github.com/UCL/STIR/issues/1390

**Review by danieldeidda — APPROVED** [review]
this makes sense to me. I am happy  for this to be approved

**Comment by KrisThielemans** [comment]
Excellent. Squash merge ok?

**Pull request merged**
